name: Build and deploy Node.js Function App

on:
  push:
    branches:
      - main  # Auto-deploys to Dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit
          - qa
          - prod

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'githubwebhooksfunctionapp'  # Path to function app
  NODE_VERSION: '22.x'  # Node.js version

jobs:
  build:
    runs-on: windows-latest
    environment: dev  # Always builds for dev environment
    permissions:
      contents: read  # Required for checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies and Build
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    environment: ${{ github.event.inputs.environment || 'dev' }}  # Auto-deploy dev, manual for others
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read  # Required for checkout

    steps:
      - name: Download Built Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTION_APP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
